### ISSUE TITLE
Request to add Russian

### ISSUE THREAD

**Issue by SergeyBiryukov** [Mte90/PTE-Bot#5]
I've shared a link to the PTE Bot with the Russian translators team and we'd like to start using it, but there's no Russian locale support at the moment. Would it be possible to add it?

The locale code is `ru_RU`, but looking at the current dropdown on http://ptebot.mte90.net, the values are a bit inconsistent, so maybe just `ru` should be used:
```
<select class="cmb2_select" name="country" id="country">
	<option value="">None</option>
	<option value="fr_fr" selected="selected">France (France)</option>
	<option value="it">Italian</option>
	<option value="pt">Portuguese</option>
</select>
```

**Comment by Mte90** [comment]
Hi @SergeyBiryukov I added russian.
For the inconsistent depends on the url of glotpress but I added russian with the locale ru :-)

**Comment by SergeyBiryukov** [comment]
> For the inconsistent depends on the url of glotpress

Yeah, but the French locale URL in GlotPress is https://translate.wordpress.org/locale/fr, not https://translate.wordpress.org/locale/fr_fr, unless I'm missing something.

Anyway, thank you, waiting for our first emails to arrive :)
